### PR TITLE
[k8s-extension] Add Managed Identity Auth support for ContainerInsights Extension

### PR DESCRIPTION
**Pull request by ganga1980**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by jonathan-innis** [comment]
@ganga1980 Can you please add E2E testing for the scenarios that are being covered for these changes here: https://github.com/AzureArcForKubernetes/azure-cli-extensions/blob/k8s-extension/public/testing/test/extensions/public/AzureMonitor.Tests.ps1

**Comment by ganga1980** [comment]
> @ganga1980 Can you please add E2E testing for the scenarios that are being covered for these changes here: https://github.com/AzureArcForKubernetes/azure-cli-extensions/blob/k8s-extension/public/testing/test/extensions/public/AzureMonitor.Tests.ps1

> @jonathan-innis , Since the tests are in different fork and branch, I will make an other PR to add the test to cover managed identity auth feature of container insights extension.  Lets get this PR merged as conformance test teams needs to run the tests on all distros.

**Comment by jonathan-innis** [comment]
> > @ganga1980 Can you please add E2E testing for the scenarios that are being covered for these changes here: https://github.com/AzureArcForKubernetes/azure-cli-extensions/blob/k8s-extension/public/testing/test/extensions/public/AzureMonitor.Tests.ps1
> 
> > @jonathan-innis , Since the tests are in different fork and branch, I will make an other PR to add the test to cover managed identity auth feature of container insights extension.  Lets get this PR merged as conformance test teams needs to run the tests on all distros.

Sure sounds good, please make sure to add these as soon as this is merged

**Review by jonathan-innis — APPROVED** [review]
🚀

**Comment by ganga1980** [comment]
> > > @ganga1980 Can you please add E2E testing for the scenarios that are being covered for these changes here: https://github.com/AzureArcForKubernetes/azure-cli-extensions/blob/k8s-extension/public/testing/test/extensions/public/AzureMonitor.Tests.ps1
> > 
> > 
> > > @jonathan-innis , Since the tests are in different fork and branch, I will make an other PR to add the test to cover managed identity auth feature of container insights extension.  Lets get this PR merged as conformance test teams needs to run the tests on all distros.
> 
> Sure sounds good, please make sure to add these as soon as this is merged

> Sure, will do. Btw, thanks for adding the container insights specific tests.

**Pull request merged**
